
\newpage

# (PART) Del 2 {-}

# Del 2 {-}
[00-2-wc-file]: <> (111.66 %)
[00-2-comment]: <> (3 sidor)

I denna del av boken följer vi utvecklingen och genomförandet av ett samhällsvetenskapligt experiment. Närmare bestämt kommer vi resonera kring ett tänkt experiment som tar avstamp inom kommunkationsforskningen, där man bland annat undersöker hur sociala medier såsom Facebook och Twitter används för att på olika sätt påverka mediepubliker. Till skillnad från den första delen av boken, där vi introducerade experiment som vetenskaplig metod, kommer del 2 att vara mer konkret och fokusera på de praktiska moment som ofta behöver beaktas i samband med planering, genomförande, och rapportering av ett experiment. Denna del av boken följer också ett kronologiskt upplägg, där vi börjar med att diskutera frågor som kommer tidigt i experiment-processen, och sedan övergår till att gå igenom praktiska frågor kring experimentets design. Vi kommer också använda oss av ett flertal andra konkreta experiment-exempel där detta krävs. Tanken med del 2 är att ge studenter ett "matlagningsrecept" för experimentella studier, där "ingredienserna" kan bytas ut och kombineras på nya sätt för att besvara nya frågeställningar. Vi är dock övertygade om att de flesta framgångsrika experiment följer vissa nödvändiga steg som successivt bygger på varandra. I denna bok kallat vi dessa steg för Förarbete (Kapitel 6), Genomförande (Kapitel 7), och Efterarbete (Kapitel 8).

**Förarbete.** I detta kapitel fokuserar vi på planeringsfasen i ett experiment. Denna fas är naturligtvis viktig oavsett vilken typ av studie vi ämnar genomföra, men på grund av att samhällsvetenskapliga experiment generellt sett vill undersöka hur en viss behandling påverkar människor, blir det avgörande att undersöka om och hur detta gjorts tidigare. Undersökningen av tidigare forskning tillåter oss att formulera (en eller flera) _forskningsfrågor_ som bygger vidare på tidigare forskningsresultat, och som därmed kan anses vara relevanta för forskningsfältet. När vi har formulerat forskningsfrågor med stöd av teoribildning och tidigare forskning har vi i nästa steg möjlighet att _operationalisera_ dessa frågor genom att omsätta kvalitativa begrepp till mätbara variabler. Detta steg kan vara så enkelt som att formulera en enkätfråga på ett sätt som visat sig vara framgångsrikt inom tidigare studier. När vi har operationaliserat forskningsfrågorna till mätbara variabler, kan vi åstadkomma den sista delen av förarbetet, i vilken vi formulerar _hypoteser_ om de statistiska samband vi förväntar oss att finna mellan våra mätvariabler. Allt detta förarbete till ett experiment är sådan information som ofta placeras i introduktionen till en uppsats eller forskningsartikel.

**Genomförande.** Detta kapitel behandlar de viktigaste praktiska stegen i experimentets genomförande. Dessa steg redovisas ofta utförligt i metoddelen av en uppsats eller forskningsartikel, och syftet med denna experimentbeskrivning är att möjliggöra upprepning av andra forskare. Genom att tidigt i forskningsprocessen göra ett _pilottest_ kan vi själva som forskare försäkra oss om att experimentet fungerar som vi har tänkt innan vi samlar in data. Därefter kommer den fullskaliga rekryteringen av _försöksdeltagare_ som nästa viktiga steg i genomförandet av ett experiment, och i detta steg är det viktigt att fundera på hur vi uppnår representativitet, samt hur vi rent praktiskt ska motivera personer att avsätta tid för att delta i studien och generera mätdata åt oss. När vi genomför ett experiment innebär det nästan alltid att vi använder någon form av _mätinstrument_ för att uppmäta hur våra försöksdeltagare svarar på en behandling. Denna behandling ingår i undersökningens _experimentella villkor_, och tanken är ofta att konstrastera en uppmätt variabel mellan ett kontrollvillkor och ett behandlingsvillkor. Exakt hur varje deltagare genomgår dessa villkor definieras av den _experimentella design_ vi beslutat oss för att använda. När vi genomför experimentet är det viktigt att alla deltagare genomgår en standardiserad _procedur_ för att minska effekten av godtyckliga bruskällor i deltagarnas responser. Experimentets genomförande avslutas med _dataanalys_ som beskriver hur vi bearbetat mätvariablerna innan vi utvärderar effekten av våra experimentella villkor, vilket kommer att bli experimentents resultat.

**Efterarbete.** I detta kapitel tar vi upp: hur man kan redovisa resultatet av ett genomfört experiment, hur vi kan diskutera den samhälleliga och forskningsmässiga relevansen av undersökningen, samt hur resultaten kan rapporteras i form av en publicerad artikel. Naturligtvis förutsätter detta sista steg att vi klarat av de tidigare stegen. När vi är klara med själva genomförandet av ett experiment, brukar det första steget i efterarbetet vara att redovisa de _resultat_ undersökningen har lett fram till. Resultaten redovisas ofta i två steg, först med deskriptiva och sedan med inferentiella statistiska metoder. Den inferentiella statistiken används för att testa de hypoteser som inledningsvis uppställdes i förarbetet till experimentet, t.ex. att vi förväntade oss att hitta signifikanta skillnader mellan deltagarnas uppmätta responser i experimentets olika villkor. Efter att vi på detta sätt redovisat förhållandet mellan våra inledningsvis förväntade resultat och våra faktiska uppmätta resultat brukar man skriva en _diskussion_ om alternativa förklaringar till undersökningens observerade resultat, samt hur experimentet kan utvecklas och förbättras genom ytterligare forskning i framtiden. Avslutningsvis kommer detta kapitel diskutera vad forskare bör tänka på vid eventuell _publicering_ av forskningsresultat.

Genomgående försöker denna lärobok täcka in två olika men näraliggande betydelser av begreppet experimentell metod: dels som en uppsättning praktiska tillvägagångssätt som bör användas för att _planera_ och genomföra en experimentell studie; och dels som ett systematiskt och standardiserat sätt att i efterhand _rapportera_ genomförandet av en studie på ett sätt som är begripligt för andra forskare. Således är denna andra del av läroboken disponerat på ett sätt som ger oss möjlighet att i typisk turordning behandla de olika aspekter av experimentell metod som man som forskare förväntas kunna redovisa när man rapporterar sina resultat till en vetenskaplig tidskrift. Men inom varje metodaspekt kommer vi också att utförligt diskutera de olika experimentella tillvägagångssätt som är relevanta i samband med planering och genomförande av en forskningsstudie.








